# Generated by Django 6.0.7 on 2026-08-12 15:35

import NaijaBay.utils
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('avatar', models.ImageField(blank=True, upload_to=NaijaBay.utils.user_avatar_upload_path, verbose_name='Avatar')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Last Name')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, choices=[('', 'Select State'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory (Abuja)'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], max_length=20, verbose_name='State')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('verified', models.BooleanField(db_index=True, default=False, verbose_name='Verified')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Staff')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username', 'email', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system_notification', 'System Notifications'), ('product_created', 'Product Created'), ('product_sold', 'Product Sold'), ('product_favorite', 'Product Favorite'), ('product_milestone_views', 'Product Milestone Views'), ('store_members', 'Store Members'), ('store_created', 'Store Created'), ('store_milestone_members', 'Store Milestone Members'), ('other', 'Other')], default='system_notification', max_length=30, verbose_name='Notification Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time Stamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(db_index=True, max_length=100, verbose_name='Store Name')),
                ('store_slug', models.SlugField(max_length=120, unique=True, verbose_name='Store Slug')),
                ('store_description', models.TextField(max_length=1500, verbose_name='Store Description')),
                ('store_type', models.CharField(choices=[('individual', 'Individual Seller'), ('registered', 'Registered Business')], db_index=True, max_length=20, verbose_name='Store Type')),
                ('store_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Store Email Address')),
                ('store_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Store Phone Number')),
                ('store_whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Store WhatsApp Number')),
                ('state', models.CharField(choices=[('', 'Select State'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory (Abuja)'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], db_index=True, max_length=25, verbose_name='Store State')),
                ('city', models.CharField(choices=[('', 'Select City'), ('aba', 'Aba'), ('umuahia', 'Umuahia'), ('ohafia', 'Ohafia'), ('arochukwu', 'Arochukwu'), ('isuikwuato', 'Isuikwuato'), ('osisioma', 'Osisioma'), ('ukwa', 'Ukwa'), ('yola', 'Yola'), ('mubi', 'Mubi'), ('numan', 'Numan'), ('jimeta', 'Jimeta'), ('ganye', 'Ganye'), ('hong', 'Hong'), ('michika', 'Michika'), ('song', 'Song'), ('uyo', 'Uyo'), ('ikot_ekpene', 'Ikot Ekpene'), ('eket', 'Eket'), ('oron', 'Oron'), ('abak', 'Abak'), ('itu', 'Itu'), ('ikot_abasi', 'Ikot Abasi'), ('etinan', 'Etinan'), ('awka', 'Awka'), ('onitsha', 'Onitsha'), ('nnewi', 'Nnewi'), ('ekwulobia', 'Ekwulobia'), ('ihiala', 'Ihiala'), ('ogbaru', 'Ogbaru'), ('aguata', 'Aguata'), ('njikoka', 'Njikoka'), ('bauchi', 'Bauchi'), ('azare', 'Azare'), ('misau', 'Misau'), ("jama'are", "Jama'Are"), ('ningi', 'Ningi'), ('katagum', 'Katagum'), ('tafawa_balewa', 'Tafawa Balewa'), ('dass', 'Dass'), ('yenagoa', 'Yenagoa'), ('brass', 'Brass'), ('nembe', 'Nembe'), ('ogbia', 'Ogbia'), ('sagbama', 'Sagbama'), ('ekeremor', 'Ekeremor'), ('kolokuma_opokuma', 'Kolokuma/Opokuma'), ('makurdi', 'Makurdi'), ('gboko', 'Gboko'), ('otukpo', 'Otukpo'), ('katsina_ala', 'Katsina-Ala'), ('vandeikya', 'Vandeikya'), ('oju', 'Oju'), ('adikpo', 'Adikpo'), ('aliade', 'Aliade'), ('maiduguri', 'Maiduguri'), ('biu', 'Biu'), ('bama', 'Bama'), ('dikwa', 'Dikwa'), ('gwoza', 'Gwoza'), ('monguno', 'Monguno'), ('konduga', 'Konduga'), ('kukawa', 'Kukawa'), ('calabar', 'Calabar'), ('ikom', 'Ikom'), ('obudu', 'Obudu'), ('ugep', 'Ugep'), ('ogoja', 'Ogoja'), ('akpabuyo', 'Akpabuyo'), ('boki', 'Boki'), ('yala', 'Yala'), ('asaba', 'Asaba'), ('warri', 'Warri'), ('sapele', 'Sapele'), ('agbor', 'Agbor'), ('ughelli', 'Ughelli'), ('ozoro', 'Ozoro'), ('effurun', 'Effurun'), ('kwale', 'Kwale'), ('burutu', 'Burutu'), ('abakaliki', 'Abakaliki'), ('afikpo', 'Afikpo'), ('onueke', 'Onueke'), ('izzi', 'Izzi'), ('ezza', 'Ezza'), ('ikwo', 'Ikwo'), ('ohaukwu', 'Ohaukwu'), ('ishielu', 'Ishielu'), ('benin_city', 'Benin City'), ('ekpoma', 'Ekpoma'), ('auchi', 'Auchi'), ('iguobazuwa', 'Iguobazuwa'), ('uromi', 'Uromi'), ('sabongida_ora', 'Sabongida-Ora'), ('igarra', 'Igarra'), ('agenebode', 'Agenebode'), ('ado_ekiti', 'Ado-Ekiti'), ('ikere_ekiti', 'Ikere-Ekiti'), ('oye_ekiti', 'Oye-Ekiti'), ('ijero_ekiti', 'Ijero-Ekiti'), ('emure_ekiti', 'Emure-Ekiti'), ('ise_ekiti', 'Ise-Ekiti'), ('ilawe_ekiti', 'Ilawe-Ekiti'), ('aramoko', 'Aramoko'), ('enugu', 'Enugu'), ('nsukka', 'Nsukka'), ('awgu', 'Awgu'), ('udi', 'Udi'), ('oji_river', 'Oji River'), ('agbani', 'Agbani'), ('nkanu', 'Nkanu'), ('enugu_ezike', 'Enugu-Ezike'), ('wuse', 'Wuse'), ('garki', 'Garki'), ('maitama', 'Maitama'), ('asokoro', 'Asokoro'), ('jabi', 'Jabi'), ('kubwa', 'Kubwa'), ('gwagwalada', 'Gwagwalada'), ('kuje', 'Kuje'), ('bwari', 'Bwari'), ('abaji', 'Abaji'), ('lugbe', 'Lugbe'), ('nyanya', 'Nyanya'), ('gombe', 'Gombe'), ('kaltungo', 'Kaltungo'), ('billiri', 'Billiri'), ('dukku', 'Dukku'), ('deba', 'Deba'), ('nafada', 'Nafada'), ('bajoga', 'Bajoga'), ('funakaye', 'Funakaye'), ('owerri', 'Owerri'), ('orlu', 'Orlu'), ('okigwe', 'Okigwe'), ('mgbidi', 'Mgbidi'), ('oguta', 'Oguta'), ('mbaise', 'Mbaise'), ('ehime_mbano', 'Ehime Mbano'), ('ideato', 'Ideato'), ('dutse', 'Dutse'), ('hadejia', 'Hadejia'), ('gumel', 'Gumel'), ('ringim', 'Ringim'), ('birnin_kudu', 'Birnin Kudu'), ('kazaure', 'Kazaure'), ('babura', 'Babura'), ('gwaram', 'Gwaram'), ('kaduna', 'Kaduna'), ('zaria', 'Zaria'), ('kafanchan', 'Kafanchan'), ('ikara', 'Ikara'), ('saminaka', 'Saminaka'), ('kachia', 'Kachia'), ('giwa', 'Giwa'), ('birnin_gwari', 'Birnin Gwari'), ('kano', 'Kano'), ('wudil', 'Wudil'), ('bichi', 'Bichi'), ('gaya', 'Gaya'), ('rano', 'Rano'), ('kibiya', 'Kibiya'), ('takai', 'Takai'), ('dawakin_tofa', 'Dawakin Tofa'), ('ungogo', 'Ungogo'), ('fagge', 'Fagge'), ('katsina', 'Katsina'), ('daura', 'Daura'), ('funtua', 'Funtua'), ('malumfashi', 'Malumfashi'), ('kankia', 'Kankia'), ('dutsin_ma', 'Dutsin-Ma'), ('bakori', 'Bakori'), ('mani', 'Mani'), ('birnin_kebbi', 'Birnin Kebbi'), ('argungu', 'Argungu'), ('yelwa', 'Yelwa'), ('zuru', 'Zuru'), ('jega', 'Jega'), ('kamba', 'Kamba'), ('bunza', 'Bunza'), ('bagudo', 'Bagudo'), ('lokoja', 'Lokoja'), ('okene', 'Okene'), ('idah', 'Idah'), ('kabba', 'Kabba'), ('anyigba', 'Anyigba'), ('ankpa', 'Ankpa'), ('dekina', 'Dekina'), ('ajaokuta', 'Ajaokuta'), ('ilorin', 'Ilorin'), ('offa', 'Offa'), ('omu_aran', 'Omu-Aran'), ('patigi', 'Patigi'), ('lafiagi', 'Lafiagi'), ('jebba', 'Jebba'), ('share', 'Share'), ('erin_ile', 'Erin-Ile'), ('ikeja', 'Ikeja'), ('lagos_island', 'Lagos Island'), ('lagos_mainland', 'Lagos Mainland'), ('yaba', 'Yaba'), ('surulere', 'Surulere'), ('ikorodu', 'Ikorodu'), ('epe', 'Epe'), ('badagry', 'Badagry'), ('ajah', 'Ajah'), ('lekki', 'Lekki'), ('victoria_island', 'Victoria Island'), ('ikoyi', 'Ikoyi'), ('apapa', 'Apapa'), ('festac', 'Festac'), ('ojo', 'Ojo'), ('alimosho', 'Alimosho'), ('agege', 'Agege'), ('ikotun', 'Ikotun'), ('egbeda', 'Egbeda'), ('isolo', 'Isolo'), ('mushin', 'Mushin'), ('oshodi', 'Oshodi'), ('maryland', 'Maryland'), ('gbagada', 'Gbagada'), ('ogba', 'Ogba'), ('magodo', 'Magodo'), ('iju', 'Iju'), ('shomolu', 'Shomolu'), ('bariga', 'Bariga'), ('lafia', 'Lafia'), ('keffi', 'Keffi'), ('akwanga', 'Akwanga'), ('nasarawa_eggon', 'Nasarawa Eggon'), ('wamba', 'Wamba'), ('doma', 'Doma'), ('karu', 'Karu'), ('toto', 'Toto'), ('minna', 'Minna'), ('suleja', 'Suleja'), ('kontagora', 'Kontagora'), ('bida', 'Bida'), ('new_bussa', 'New Bussa'), ('lapai', 'Lapai'), ('agaie', 'Agaie'), ('wushishi', 'Wushishi'), ('abeokuta', 'Abeokuta'), ('ijebu_ode', 'Ijebu-Ode'), ('sagamu', 'Sagamu'), ('ilaro', 'Ilaro'), ('ota', 'Ota'), ('ifo', 'Ifo'), ('sango_ota', 'Sango-Ota'), ('ijebu_igbo', 'Ijebu-Igbo'), ('ayetoro', 'Ayetoro'), ('owode', 'Owode'), ('akure', 'Akure'), ('ondo', 'Ondo'), ('ore', 'Ore'), ('okitipupa', 'Okitipupa'), ('ikare', 'Ikare'), ('owo', 'Owo'), ('idanre', 'Idanre'), ('ile_oluji', 'Ile-Oluji'), ('oka', 'Oka'), ('osogbo', 'Osogbo'), ('ile_ife', 'Ile-Ife'), ('ilesha', 'Ilesha'), ('ede', 'Ede'), ('ikirun', 'Ikirun'), ('iwo', 'Iwo'), ('ejigbo', 'Ejigbo'), ('ikire', 'Ikire'), ('ila', 'Ila'), ('gbongan', 'Gbongan'), ('ibadan', 'Ibadan'), ('oyo', 'Oyo'), ('ogbomosho', 'Ogbomosho'), ('saki', 'Saki'), ('iseyin', 'Iseyin'), ('eruwa', 'Eruwa'), ('kisi', 'Kisi'), ('igbo_ora', 'Igbo-Ora'), ('lanlate', 'Lanlate'), ('moniya', 'Moniya'), ('jos', 'Jos'), ('bukuru', 'Bukuru'), ('pankshin', 'Pankshin'), ('langtang', 'Langtang'), ('shendam', 'Shendam'), ('mangu', 'Mangu'), ('bokkos', 'Bokkos'), ('bassa', 'Bassa'), ('port_harcourt', 'Port Harcourt'), ('obio_akpor', 'Obio/Akpor'), ('bonny', 'Bonny'), ('degema', 'Degema'), ('ikwerre', 'Ikwerre'), ('oyigbo', 'Oyigbo'), ('ahoada', 'Ahoada'), ('okrika', 'Okrika'), ('eleme', 'Eleme'), ('emuoha', 'Emuoha'), ('tai', 'Tai'), ('gokana', 'Gokana'), ('khana', 'Khana'), ('sokoto', 'Sokoto'), ('tambuwal', 'Tambuwal'), ('gwadabawa', 'Gwadabawa'), ('wurno', 'Wurno'), ('shagari', 'Shagari'), ('binji', 'Binji'), ('bodinga', 'Bodinga'), ('goronyo', 'Goronyo'), ('jalingo', 'Jalingo'), ('wukari', 'Wukari'), ('bali', 'Bali'), ('gembu', 'Gembu'), ('zing', 'Zing'), ('sardauna', 'Sardauna'), ('takum', 'Takum'), ('ibi', 'Ibi'), ('damaturu', 'Damaturu'), ('potiskum', 'Potiskum'), ('gashua', 'Gashua'), ('nguru', 'Nguru'), ('gujba', 'Gujba'), ('buni_yadi', 'Buni Yadi'), ('geidam', 'Geidam'), ('yunusari', 'Yunusari'), ('gusau', 'Gusau'), ('kaura_namoda', 'Kaura-Namoda'), ('anka', 'Anka'), ('talata_mafara', 'Talata Mafara'), ('shinkafi', 'Shinkafi'), ('maradun', 'Maradun'), ('bakura', 'Bakura'), ('bungudu', 'Bungudu')], db_index=True, max_length=100, verbose_name='Store City')),
                ('address', models.TextField(verbose_name='Store Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=NaijaBay.utils.store_logo_upload_path, verbose_name='Store Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=NaijaBay.utils.store_banner_upload_path, verbose_name='Store Banner')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Store Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Store Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Store Updated At')),
                ('members', models.ManyToManyField(blank=True, related_name='store_members', to=settings.AUTH_USER_MODEL)),
                ('store_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_user', to=settings.AUTH_USER_MODEL, verbose_name='Store User')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10, verbose_name='Amount Paid')),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Transaction Reference')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='Payment Gateway')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email', 'state'], name='accounts_us_usernam_ac5a80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email', 'verified', 'state'], name='accounts_us_usernam_a2f559_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email', 'is_active', 'date_joined'], name='accounts_us_usernam_ae335c_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'read', '-timestamp'], name='accounts_no_user_id_ee4c71_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_name', 'store_type', '-created_at'], name='accounts_st_store_n_c1cd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_user', 'store_name', 'store_type', 'state', 'city'], name='accounts_st_store_u_d1369a_idx'),
        ),
    ]
