# Generated by Django 6.0.7 on 2026-08-12 11:12

import NaijaBay.utils
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, verbose_name='Product Name')),
                ('product_slug', models.SlugField(max_length=200, unique=True, verbose_name='Product Slug')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1000.00')), django.core.validators.MaxValueValidator(Decimal('999999999'))], verbose_name='Product Price')),
                ('category', models.CharField(choices=[('', 'Select Category'), ('phones_tablets', 'Phones & Tablets'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('real_estate', 'Real Estate'), ('fashion', 'Fashion'), ('home_garden', 'Home & Garden'), ('jobs', 'Jobs'), ('services', 'Services'), ('animals_pets', 'Animals & Pets'), ('food_agriculture', 'Food & Agriculture'), ('health_beauty', 'Health & Beauty'), ('kids_baby', 'Kids & Baby'), ('sports_outdoor', 'Sports & Outdoor'), ('books_music_movies', 'Books, Music & Movies')], db_index=True, max_length=30, verbose_name='Category')),
                ('sub_category', models.CharField(choices=[('', 'Select Sub Category'), ('mobile_phones', 'Mobile Phones'), ('tablets', 'Tablets'), ('phone_accessories', 'Phone Accessories'), ('smartwatches', 'Smartwatches'), ('phone_parts', 'Phone Parts'), ('laptops_computers', 'Laptops Computers'), ('tvs', 'TVs'), ('audio_music', 'Audio Music'), ('cameras', 'Cameras'), ('gaming', 'Gaming'), ('printers', 'Printers'), ('computer_accessories', 'Computer Accessories'), ('cars', 'Cars'), ('motorcycles', 'Motorcycles'), ('trucks_buses', 'Trucks Buses'), ('vehicle_parts', 'Vehicle Parts'), ('boats', 'Boats'), ('bicycles', 'Bicycles'), ('houses_rent', 'Houses Rent'), ('houses_sale', 'Houses Sale'), ('flats_apartments', 'Flats Apartments'), ('land_plots', 'Land Plots'), ('commercial_property', 'Commercial Property'), ('short_let', 'Short Let'), ('mens_clothing', 'Mens Clothing'), ('womens_clothing', 'Womens Clothing'), ('kids_clothing', 'Kids Clothing'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('watches_jewelry', 'Watches Jewelry'), ('traditional_wear', 'Traditional Wear'), ('furniture', 'Furniture'), ('kitchen_appliances', 'Kitchen Appliances'), ('bedding_linen', 'Bedding Linen'), ('garden_outdoor', 'Garden Outdoor'), ('home_decor', 'Home Decor'), ('generators', 'Generators'), ('air_conditioners', 'Air Conditioners'), ('accounting_finance', 'Accounting Finance'), ('admin_office', 'Admin Office'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('it_telecoms', 'IT & Telecoms'), ('sales_marketing', 'Sales Marketing'), ('teaching', 'Teaching'), ('driving_logistics', 'Driving Logistics'), ('repair_maintenance', 'Repair Maintenance'), ('cleaning_services', 'Cleaning Services'), ('catering', 'Catering'), ('event_planning', 'Event Planning'), ('photography', 'Photography'), ('web_dev', 'Web Dev'), ('tutoring', 'Tutoring'), ('moving_delivery', 'Moving Delivery'), ('dogs', 'Dogs'), ('cats', 'Cats'), ('birds', 'Birds'), ('fish_aquarium', 'Fish Aquarium'), ('pet_accessories', 'Pet Accessories'), ('livestock', 'Livestock'), ('farm_produce', 'Farm Produce'), ('processed_food', 'Processed Food'), ('farming_equipment', 'Farming Equipment'), ('seeds_fertilizers', 'Seeds Fertilizers'), ('skincare', 'Skincare'), ('hair_products', 'Hair Products'), ('vitamins', 'Vitamins'), ('medical_equipment', 'Medical Equipment'), ('gym_fitness', 'Gym Fitness'), ('perfumes', 'Perfumes'), ('baby_clothing', 'Baby Clothing'), ('toys_games', 'Toys Games'), ('baby_gear', 'Baby Gear'), ('school_supplies', 'School Supplies'), ('football', 'Football'), ('gym_equipment', 'Gym Equipment'), ('outdoor_camping', 'Outdoor Camping'), ('cycling', 'Cycling'), ('books_textbooks', 'Books Textbooks'), ('music_instruments', 'Music Instruments'), ('movies_dvds', 'Movies Dvds'), ('video_games', 'Video Games')], db_index=True, max_length=20, verbose_name='Sub Category')),
                ('condition', models.CharField(choices=[('', 'No Condition'), ('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], db_index=True, max_length=20, verbose_name='Product Condition')),
                ('color', models.CharField(max_length=20, verbose_name='Product Color')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Product Quantity')),
                ('negotiable', models.BooleanField(default=False, verbose_name='Price Negotiable')),
                ('state', models.CharField(choices=[('', 'Select State'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory (Abuja)'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], db_index=True, max_length=25, verbose_name='Product State')),
                ('city', models.CharField(choices=[('', 'Select City'), ('aba', 'Aba'), ('umuahia', 'Umuahia'), ('ohafia', 'Ohafia'), ('arochukwu', 'Arochukwu'), ('isuikwuato', 'Isuikwuato'), ('osisioma', 'Osisioma'), ('ukwa', 'Ukwa'), ('yola', 'Yola'), ('mubi', 'Mubi'), ('numan', 'Numan'), ('jimeta', 'Jimeta'), ('ganye', 'Ganye'), ('hong', 'Hong'), ('michika', 'Michika'), ('song', 'Song'), ('uyo', 'Uyo'), ('ikot_ekpene', 'Ikot Ekpene'), ('eket', 'Eket'), ('oron', 'Oron'), ('abak', 'Abak'), ('itu', 'Itu'), ('ikot_abasi', 'Ikot Abasi'), ('etinan', 'Etinan'), ('awka', 'Awka'), ('onitsha', 'Onitsha'), ('nnewi', 'Nnewi'), ('ekwulobia', 'Ekwulobia'), ('ihiala', 'Ihiala'), ('ogbaru', 'Ogbaru'), ('aguata', 'Aguata'), ('njikoka', 'Njikoka'), ('bauchi', 'Bauchi'), ('azare', 'Azare'), ('misau', 'Misau'), ("jama'are", "Jama'Are"), ('ningi', 'Ningi'), ('katagum', 'Katagum'), ('tafawa_balewa', 'Tafawa Balewa'), ('dass', 'Dass'), ('yenagoa', 'Yenagoa'), ('brass', 'Brass'), ('nembe', 'Nembe'), ('ogbia', 'Ogbia'), ('sagbama', 'Sagbama'), ('ekeremor', 'Ekeremor'), ('kolokuma_opokuma', 'Kolokuma/Opokuma'), ('makurdi', 'Makurdi'), ('gboko', 'Gboko'), ('otukpo', 'Otukpo'), ('katsina_ala', 'Katsina-Ala'), ('vandeikya', 'Vandeikya'), ('oju', 'Oju'), ('adikpo', 'Adikpo'), ('aliade', 'Aliade'), ('maiduguri', 'Maiduguri'), ('biu', 'Biu'), ('bama', 'Bama'), ('dikwa', 'Dikwa'), ('gwoza', 'Gwoza'), ('monguno', 'Monguno'), ('konduga', 'Konduga'), ('kukawa', 'Kukawa'), ('calabar', 'Calabar'), ('ikom', 'Ikom'), ('obudu', 'Obudu'), ('ugep', 'Ugep'), ('ogoja', 'Ogoja'), ('akpabuyo', 'Akpabuyo'), ('boki', 'Boki'), ('yala', 'Yala'), ('asaba', 'Asaba'), ('warri', 'Warri'), ('sapele', 'Sapele'), ('agbor', 'Agbor'), ('ughelli', 'Ughelli'), ('ozoro', 'Ozoro'), ('effurun', 'Effurun'), ('kwale', 'Kwale'), ('burutu', 'Burutu'), ('abakaliki', 'Abakaliki'), ('afikpo', 'Afikpo'), ('onueke', 'Onueke'), ('izzi', 'Izzi'), ('ezza', 'Ezza'), ('ikwo', 'Ikwo'), ('ohaukwu', 'Ohaukwu'), ('ishielu', 'Ishielu'), ('benin_city', 'Benin City'), ('ekpoma', 'Ekpoma'), ('auchi', 'Auchi'), ('iguobazuwa', 'Iguobazuwa'), ('uromi', 'Uromi'), ('sabongida_ora', 'Sabongida-Ora'), ('igarra', 'Igarra'), ('agenebode', 'Agenebode'), ('ado_ekiti', 'Ado-Ekiti'), ('ikere_ekiti', 'Ikere-Ekiti'), ('oye_ekiti', 'Oye-Ekiti'), ('ijero_ekiti', 'Ijero-Ekiti'), ('emure_ekiti', 'Emure-Ekiti'), ('ise_ekiti', 'Ise-Ekiti'), ('ilawe_ekiti', 'Ilawe-Ekiti'), ('aramoko', 'Aramoko'), ('enugu', 'Enugu'), ('nsukka', 'Nsukka'), ('awgu', 'Awgu'), ('udi', 'Udi'), ('oji_river', 'Oji River'), ('agbani', 'Agbani'), ('nkanu', 'Nkanu'), ('enugu_ezike', 'Enugu-Ezike'), ('wuse', 'Wuse'), ('garki', 'Garki'), ('maitama', 'Maitama'), ('asokoro', 'Asokoro'), ('jabi', 'Jabi'), ('kubwa', 'Kubwa'), ('gwagwalada', 'Gwagwalada'), ('kuje', 'Kuje'), ('bwari', 'Bwari'), ('abaji', 'Abaji'), ('lugbe', 'Lugbe'), ('nyanya', 'Nyanya'), ('gombe', 'Gombe'), ('kaltungo', 'Kaltungo'), ('billiri', 'Billiri'), ('dukku', 'Dukku'), ('deba', 'Deba'), ('nafada', 'Nafada'), ('bajoga', 'Bajoga'), ('funakaye', 'Funakaye'), ('owerri', 'Owerri'), ('orlu', 'Orlu'), ('okigwe', 'Okigwe'), ('mgbidi', 'Mgbidi'), ('oguta', 'Oguta'), ('mbaise', 'Mbaise'), ('ehime_mbano', 'Ehime Mbano'), ('ideato', 'Ideato'), ('dutse', 'Dutse'), ('hadejia', 'Hadejia'), ('gumel', 'Gumel'), ('ringim', 'Ringim'), ('birnin_kudu', 'Birnin Kudu'), ('kazaure', 'Kazaure'), ('babura', 'Babura'), ('gwaram', 'Gwaram'), ('kaduna', 'Kaduna'), ('zaria', 'Zaria'), ('kafanchan', 'Kafanchan'), ('ikara', 'Ikara'), ('saminaka', 'Saminaka'), ('kachia', 'Kachia'), ('giwa', 'Giwa'), ('birnin_gwari', 'Birnin Gwari'), ('kano', 'Kano'), ('wudil', 'Wudil'), ('bichi', 'Bichi'), ('gaya', 'Gaya'), ('rano', 'Rano'), ('kibiya', 'Kibiya'), ('takai', 'Takai'), ('dawakin_tofa', 'Dawakin Tofa'), ('ungogo', 'Ungogo'), ('fagge', 'Fagge'), ('katsina', 'Katsina'), ('daura', 'Daura'), ('funtua', 'Funtua'), ('malumfashi', 'Malumfashi'), ('kankia', 'Kankia'), ('dutsin_ma', 'Dutsin-Ma'), ('bakori', 'Bakori'), ('mani', 'Mani'), ('birnin_kebbi', 'Birnin Kebbi'), ('argungu', 'Argungu'), ('yelwa', 'Yelwa'), ('zuru', 'Zuru'), ('jega', 'Jega'), ('kamba', 'Kamba'), ('bunza', 'Bunza'), ('bagudo', 'Bagudo'), ('lokoja', 'Lokoja'), ('okene', 'Okene'), ('idah', 'Idah'), ('kabba', 'Kabba'), ('anyigba', 'Anyigba'), ('ankpa', 'Ankpa'), ('dekina', 'Dekina'), ('ajaokuta', 'Ajaokuta'), ('ilorin', 'Ilorin'), ('offa', 'Offa'), ('omu_aran', 'Omu-Aran'), ('patigi', 'Patigi'), ('lafiagi', 'Lafiagi'), ('jebba', 'Jebba'), ('share', 'Share'), ('erin_ile', 'Erin-Ile'), ('ikeja', 'Ikeja'), ('lagos_island', 'Lagos Island'), ('lagos_mainland', 'Lagos Mainland'), ('yaba', 'Yaba'), ('surulere', 'Surulere'), ('ikorodu', 'Ikorodu'), ('epe', 'Epe'), ('badagry', 'Badagry'), ('ajah', 'Ajah'), ('lekki', 'Lekki'), ('victoria_island', 'Victoria Island'), ('ikoyi', 'Ikoyi'), ('apapa', 'Apapa'), ('festac', 'Festac'), ('ojo', 'Ojo'), ('alimosho', 'Alimosho'), ('agege', 'Agege'), ('ikotun', 'Ikotun'), ('egbeda', 'Egbeda'), ('isolo', 'Isolo'), ('mushin', 'Mushin'), ('oshodi', 'Oshodi'), ('maryland', 'Maryland'), ('gbagada', 'Gbagada'), ('ogba', 'Ogba'), ('magodo', 'Magodo'), ('iju', 'Iju'), ('shomolu', 'Shomolu'), ('bariga', 'Bariga'), ('lafia', 'Lafia'), ('keffi', 'Keffi'), ('akwanga', 'Akwanga'), ('nasarawa_eggon', 'Nasarawa Eggon'), ('wamba', 'Wamba'), ('doma', 'Doma'), ('karu', 'Karu'), ('toto', 'Toto'), ('minna', 'Minna'), ('suleja', 'Suleja'), ('kontagora', 'Kontagora'), ('bida', 'Bida'), ('new_bussa', 'New Bussa'), ('lapai', 'Lapai'), ('agaie', 'Agaie'), ('wushishi', 'Wushishi'), ('abeokuta', 'Abeokuta'), ('ijebu_ode', 'Ijebu-Ode'), ('sagamu', 'Sagamu'), ('ilaro', 'Ilaro'), ('ota', 'Ota'), ('ifo', 'Ifo'), ('sango_ota', 'Sango-Ota'), ('ijebu_igbo', 'Ijebu-Igbo'), ('ayetoro', 'Ayetoro'), ('owode', 'Owode'), ('akure', 'Akure'), ('ondo', 'Ondo'), ('ore', 'Ore'), ('okitipupa', 'Okitipupa'), ('ikare', 'Ikare'), ('owo', 'Owo'), ('idanre', 'Idanre'), ('ile_oluji', 'Ile-Oluji'), ('oka', 'Oka'), ('osogbo', 'Osogbo'), ('ile_ife', 'Ile-Ife'), ('ilesha', 'Ilesha'), ('ede', 'Ede'), ('ikirun', 'Ikirun'), ('iwo', 'Iwo'), ('ejigbo', 'Ejigbo'), ('ikire', 'Ikire'), ('ila', 'Ila'), ('gbongan', 'Gbongan'), ('ibadan', 'Ibadan'), ('oyo', 'Oyo'), ('ogbomosho', 'Ogbomosho'), ('saki', 'Saki'), ('iseyin', 'Iseyin'), ('eruwa', 'Eruwa'), ('kisi', 'Kisi'), ('igbo_ora', 'Igbo-Ora'), ('lanlate', 'Lanlate'), ('moniya', 'Moniya'), ('jos', 'Jos'), ('bukuru', 'Bukuru'), ('pankshin', 'Pankshin'), ('langtang', 'Langtang'), ('shendam', 'Shendam'), ('mangu', 'Mangu'), ('bokkos', 'Bokkos'), ('bassa', 'Bassa'), ('port_harcourt', 'Port Harcourt'), ('obio_akpor', 'Obio/Akpor'), ('bonny', 'Bonny'), ('degema', 'Degema'), ('ikwerre', 'Ikwerre'), ('oyigbo', 'Oyigbo'), ('ahoada', 'Ahoada'), ('okrika', 'Okrika'), ('eleme', 'Eleme'), ('emuoha', 'Emuoha'), ('tai', 'Tai'), ('gokana', 'Gokana'), ('khana', 'Khana'), ('sokoto', 'Sokoto'), ('tambuwal', 'Tambuwal'), ('gwadabawa', 'Gwadabawa'), ('wurno', 'Wurno'), ('shagari', 'Shagari'), ('binji', 'Binji'), ('bodinga', 'Bodinga'), ('goronyo', 'Goronyo'), ('jalingo', 'Jalingo'), ('wukari', 'Wukari'), ('bali', 'Bali'), ('gembu', 'Gembu'), ('zing', 'Zing'), ('sardauna', 'Sardauna'), ('takum', 'Takum'), ('ibi', 'Ibi'), ('damaturu', 'Damaturu'), ('potiskum', 'Potiskum'), ('gashua', 'Gashua'), ('nguru', 'Nguru'), ('gujba', 'Gujba'), ('buni_yadi', 'Buni Yadi'), ('geidam', 'Geidam'), ('yunusari', 'Yunusari'), ('gusau', 'Gusau'), ('kaura_namoda', 'Kaura-Namoda'), ('anka', 'Anka'), ('talata_mafara', 'Talata Mafara'), ('shinkafi', 'Shinkafi'), ('maradun', 'Maradun'), ('bakura', 'Bakura'), ('bungudu', 'Bungudu')], db_index=True, max_length=20, verbose_name='Product City')),
                ('contact_methods', models.JSONField(default=list, validators=[NaijaBay.utils.validate_contact_methods], verbose_name='Contact Methods')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sold', models.BooleanField(db_index=True, default=False, verbose_name='Sold')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Product Favorites')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Product User')),
                ('views', models.ManyToManyField(blank=True, related_name='viewed_products', to=settings.AUTH_USER_MODEL, verbose_name='Product Views')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=NaijaBay.utils.product_images_upload_path, verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='products_pr_product_097795_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_user'], name='products_pr_product_f72f35_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='products_pr_active_7d1f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_user', 'product_name'], name='products_pr_product_558743_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sub_category'], name='products_pr_categor_b2b194_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_user', 'category', 'sub_category', 'active'], name='products_pr_product_44225e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['state', 'city'], name='products_pr_state_d219d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'state', 'city'], name='products_pr_categor_3efbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['created_at'], name='products_pr_created_d679ec_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='products_pr_product_3d7874_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'created_at'], name='products_pr_product_9c1756_idx'),
        ),
    ]
