# Generated by Django 6.0.7 on 2026-08-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Category Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx'), models.Index(fields=['name', 'slug'], name='core_catego_name_1069b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='State Name')),
                ('slug', models.SlugField(unique=True, verbose_name='State Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_state_slug_8e574b_idx'), models.Index(fields=['name', 'slug'], name='core_state_name_7a4828_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='City Name')),
                ('slug', models.SlugField(verbose_name='City Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['state', 'name'],
                'indexes': [models.Index(fields=['slug'], name='core_city_slug_72b672_idx'), models.Index(fields=['state', 'name'], name='core_city_state_i_fa1a0a_idx'), models.Index(fields=['state', 'name', 'slug'], name='core_city_state_i_cf6025_idx')],
                'constraints': [models.UniqueConstraint(fields=('state', 'name'), name='unique_city_per_state')],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Sub Category Name')),
                ('slug', models.SlugField(verbose_name='Sub Category Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['slug'], name='core_subcat_slug_56ef66_idx'), models.Index(fields=['category', 'name'], name='core_subcat_categor_93725f_idx'), models.Index(fields=['category', 'name', 'slug'], name='core_subcat_categor_37c611_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_per_category')],
            },
        ),
    ]
